### ISSUE TITLE
Unable to launch firefox browser in Android device using appium.

### ISSUE THREAD

**Issue by bramari** [appium/appium-geckodriver#17]
Hi,

I'm unable to launch the firefox browser in an Android real device using appium. Please help in fixing.

**Below is the code:**

An unknown server-side error occurred while processing the command. Original error: geckodriver.exe binary cannot be found in PATH. Please make sure it is present on your system (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2.88 seconds
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'XXX', ip: '192.168.1.36', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: driver.version: RemoteWebDriver
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:255)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:138)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:175)
	at com.mobile.base.DriverScript.isRunnableMobileWeb(DriverScript.java:514)
	at testscripts.Flow_HealthFirst_USI.flow_TC001(Flow_HealthFirst_USI.java:167)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by mykola-mokhnach** [comment]
What exactly is unclear in this error message?

**Comment by bramari** [comment]
> What exactly is unclear in this error message?

I'm not sure if I'm setting capabilities correctly for firefox. Can you please help me in setting them and also how to set binary path for gecko driver.

**Comment by bramari** [comment]
@mykola-mokhnach 
I have set the gecko driver path in environment variables as well. But still throwing error that geckodriver.exe path not found.

**Comment by Skandha-commits** [comment]
> What exactly is unclear in this error message?

@mykola-mokhnach :

Error is highlighted in bold

_http://127.0.0.1:4723/wd/hub ======= real device
Capabilities [{deviceType=androiddevice, noReset=True, moz:firefoxOptions={"androidPackage":"org.mozilla.firefox","deviceName":"Samsung","deviceUDID":"RZ5R419DE7J"}, version=, deviceName=androiddevice, deviceReadyTimeout=400, fullReset=False, platform=ANDROID, newCommandTimeout=180, acceptInsecureCerts=true, automationName=Gecko, browserName=firefox, platformName=Android, udid=RZ5R419DE7J}]_
**org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: geckodriver.exe binary cannot be found in PATH. Please make sure it is present on your system (WARNING: The server did not provide any stacktrace information)**
Command duration or timeout: 3.45 seconds
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'XXXXXX', ip: '192.168.55.104', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: driver.version: RemoteWebDriver
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:255)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:138)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:175)
	at com.mobile.base.DriverScript.isRunnableMobileWeb(DriverScript.java:521)
	at testscripts.Flow_HealthFirst_USI.flow_TC001(Flow_HealthFirst_USI.java:167)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Below is my code:**

if(Util.ucase(mobileOSPlatform).equals("ANDROID")){
                  capabilities = DesiredCapabilities.android();
                  capabilities.setCapability("deviceType", "androiddevice");
                  capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "androiddevice");                               
                   capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "firefox");    //Chrome
                   capabilities.setCapability(AndroidMobileCapabilityType.DEVICE_READY_TIMEOUT, 400);
                                      capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 180);
                                      capabilities.setCapability(MobileCapabilityType.NO_RESET, "True");
                                      capabilities.setCapability(MobileCapabilityType.FULL_RESET,"False");
                                      capabilities.setCapability("automationName", "Gecko"); 
                                      capabilities.setCapability("platformName", "Android");
                                      capabilities.setCapability("udid", deviceId);
                                      JSONObject firefoxoptions=new JSONObject();
                                      firefoxoptions.put("androidPackage", "org.mozilla.firefox");
                                      firefoxoptions.put("deviceUDID",deviceId);
                                      firefoxoptions.put("deviceName", deviceName);                                     
                                      capabilities.setCapability("moz:firefoxOptions",firefoxoptions);										                                    
                                     capabilities.setAcceptInsecureCerts(true);
                         }                                  
System.out.println(capabilities);                                     
 if(Util.ucase(mobileOSPlatform).equals("ANDROID")){
              mobileDriver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
              mobileDriver.manage().timeouts().implicitlyWait(implicitWait, TimeUnit.SECONDS);
	    }

> What exactly is unclear in this error message?

**Comment by mykola-mokhnach** [comment]
You could try apple the troubleshooting guide at https://github.com/appium/java-client/blob/master/docs/environment.md to make sure the Appium process contains the correct PATH value

**Comment by stefanhuber** [comment]
On Windows you have to restart the terminal after setting the PATH variable...

**Comment by jayalathaKrishnaraj** [comment]
**Is the above problem is resolved ? Im trying to automate my custome web application in firefox  browser application in android mobile Im getting this error** 

[b07ec0e4][AppiumDriver@dbc6] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: adb error: fchown() failed uid: 0 gid: 0: Operation not permitted
    at errorFromW3CJsonCode (C:\Users\Jayalatha Krishna\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1110:25)
    at ProxyRequestError.getActualError (C:\Users\Jayalatha Krishna\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:979:14)
    at GeckoProxy.command (C:\Users\Jayalatha Krishna\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:357:19)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at GeckoDriverServer.start (C:\Users\Jayalatha Krishna\.appium\node_modules\appium-geckodriver\lib\gecko.js:252:7)
    at GeckoDriver.createSession (C:\Users\Jayalatha Krishna\.appium\node_modules\appium-geckodriver\lib\driver.js:71:18)
    at AppiumDriver.createSession (C:\Users\Jayalatha Krishna\AppData\Roaming\npm\node_modules\appium\lib\appium.js:379:35)
[b07ec0e4][HTTP] <-- POST /session 500 46996 ms - 1379
[HTTP] Request idempotency key: 983b91ab-0bdc-4064-a8fd-e9672fac1b89
[HTTP] --> POST /session {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"Windows","appium:automationName":"Gecko","browserName":"firefox","appium:androidStorage":"sdcard","moz:firefoxOptions":{"androidPackage":"org.mozilla.firefox","androidDeviceSerial":"A6Y9VOVW6DORJBZP"}}}}
[AppiumDriver@dbc6] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{}],"alwaysMatch":{"platformName":"Windows","appium:automationName":"Gecko","browserName":"firefox","appium:androidStorage":"sdcard","moz:firefoxOptions":{"androidPackage":"org.mozilla.firefox","androidDeviceSerial":"A6Y9VOVW6DORJBZP"}}}]
[AppiumDriver@dbc6] Event 'newSessionRequested' logged at 1754632497096 (11:24:57 GMT+0530 (India Standard Time))
[Appium] Attempting to find matching driver for automationName 'Gecko' and platformName 'Windows'
[Appium] The 'gecko' driver was installed and matched caps.
[Appium] Will require it at C:\Users\Jayalatha Krishna\.appium\node_modules\appium-geckodriver
[Appium] Requiring driver at C:\Users\Jayalatha Krishna\.appium\node_modules\appium-geckodriver\build\index.js
[AppiumDriver@dbc6] Appium v2.19.0 creating new GeckoDriver (v1.4.3) session
[AppiumDriver@dbc6] Checking BaseDriver versions for Appium and GeckoDriver
[AppiumDriver@dbc6] Appium's BaseDriver version is 9.18.0
[AppiumDriver@dbc6] GeckoDriver's BaseDriver version is 9.18.0
[GeckoDriver@08f4]
[GeckoDriver@08f4] Creating session with W3C capabilities: {
  "alwaysMatch": {
    "platformName": "Windows",
    "browserName": "firefox",
    "moz:firefoxOptions": {
      "androidPackage": "org.mozilla.firefox",
      "androidDeviceSerial": "A6Y9VOVW6DORJBZP"
    },
    "appium:automationName": "Gecko",
    "appium:androidStorage": "sdcard"
  },
  "firstMatch": [
    {}
  ]
}
[387eebc0][GeckoDriver@08f4] Session created with session id: 387eebc0-d46c-457f-bcd1-4749292eb564
[387eebc0][GeckoDriver@08f4] Starting 'C:\Users\Jayalatha Krishna\.appium\node_modules\appium-geckodriver\geckodriver.exe' with args ["-p","5200","--android-storage","sdcard"]
[387eebc0][GeckoDriver@08f4] GeckoProxy options: {"server":"127.0.0.1","port":5200,"base":"","keepAlive":true,"scheme":"http","reqBasePath":"","sessionId":null,"timeout":240000}
[387eebc0][GeckoDriver@08f4] Matched '/status' to command name 'getStatus'
[387eebc0][GeckoDriver@08f4] Proxying [GET /status] to [GET http://127.0.0.1:5200/status] with no body
[387eebc0][GeckoDriver@08f4] connect ECONNREFUSED 127.0.0.1:5200
[387eebc0][GeckoDriver@08f4] [geckodriver.exe] 1754632497264    geckodriver     WARN    --android-storage argument is deprecated and will be removed soon.
[387eebc0][GeckoDriver@08f4] [geckodriver.exe] 1754632497265    geckodriver     INFO    Listening on 127.0.0.1:5200
[387eebc0][GeckoDriver@08f4] Matched '/status' to command name 'getStatus'
[387eebc0][GeckoDriver@08f4] Proxying [GET /status] to [GET http://127.0.0.1:5200/status] with no body
[387eebc0][GeckoDriver@08f4] Got response with status 200: {"value":{"message":"","ready":true}}
[387eebc0][GeckoDriver@08f4] Matched '/session' to command name 'createSession'
[387eebc0][GeckoDriver@08f4] Proxying [POST /session] to [POST http://127.0.0.1:5200/session] with body: {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"browserName":"firefox","platformName":"windows","moz:firefoxOptions":{"androidPackage":"org.mozilla.firefox","androidDeviceSerial":"A6Y9VOVW6DORJBZP"}}}}
[387eebc0][GeckoDriver@08f4] [geckodriver.exe] 1754632506583    mozdevice       INFO    Device is unrooted
[387eebc0][GeckoDriver@08f4] Got response with status 500: {"value":{"error":"unknown error","message":"adb error: fchown() failed uid: 0 gid: 0: Operation not permitted","stacktrace":""}}
[387eebc0][W3C] Matched W3C error code 'unknown error' to UnknownError
[387eebc0][GeckoDriver@08f4] Ending Gecko Driver session
[387eebc0][GeckoDriver@08f4] geckodriver.exe has exited with code null, signal SIGTERM
[387eebc0][AppiumDriver@dbc6] Event 'newSessionStarted' logged at 1754632544044 (11:25:44 GMT+0530 (India Standard Time))
[387eebc0][AppiumDriver@dbc6] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: adb error: fchown() failed uid: 0 gid: 0: Operation not permitted
    at errorFromW3CJsonCode (C:\Users\Jayalatha Krishna\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1110:25)
    at ProxyRequestError.getActualError (C:\Users\Jayalatha Krishna\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:979:14)
    at GeckoProxy.command (C:\Users\Jayalatha Krishna\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:357:19)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at GeckoDriverServer.start (C:\Users\Jayalatha Krishna\.appium\node_modules\appium-geckodriver\lib\gecko.js:252:7)
    at GeckoDriver.createSession (C:\Users\Jayalatha Krishna\.appium\node_modules\appium-geckodriver\lib\driver.js:71:18)
    at AppiumDriver.createSession (C:\Users\Jayalatha Krishna\AppData\Roaming\npm\node_modules\appium\lib\appium.js:379:35)
[387eebc0][HTTP] <-- POST /session 500 46950 ms - 1379
