### ISSUE TITLE
adb error: fchown failed: Operation not permitted

### ISSUE THREAD

**Issue by stefanhuber** [appium/appium-geckodriver#27]
**selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: adb error: fchown failed: Operation not permitted**

On Samsung S21 (Android 12) the following configuration leads to an error:

```
{
    'platformName': 'Windows',
    'appium:automationName': 'Gecko',
    'appium:deviceName': 'Samsung S21',
    'browserName': 'firefox',
    'acceptInsecureCerts': True,
    'moz:firefoxOptions': {
        'androidPackage': 'org.mozilla.firefox',
    }
}
```

The configuration works on Samsung S9 (Android 10).

```
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: adb error: fchown failed: Operation not permitted
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: adb error: fchown failed: Operation not permitted
    at errorFromW3CJsonCode (C:\Users\...\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:780:25)
    at ProxyRequestError.getActualError (C:\Users\...\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:663:14)
    at GeckoProxy.command (C:\Users\...\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:272:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at GeckoDriverServer.start (C:\Users\...\AppData\Roaming\npm\node_modules\appium\node_modules\appium-geckodriver\lib\gecko.js:185:5)
    at GeckoDriver.createSession (C:\Users\...\AppData\Roaming\npm\node_modules\appium\node_modules\appium-geckodriver\lib\driver.js:59:7)
    at AppiumDriver.createSession (C:\Users\...\AppData\Roaming\npm\node_modules\appium\lib\appium.js:387:35)
```

**Comment by mykola-mokhnach** [comment]
Could you please provide the full server log with verbose logging enabled?

**Comment by stefanhuber** [comment]
For whatever reason it is working now, with the exact same setup...

**Comment by jayalathaKrishnaraj** [comment]
Im facing the issue unable to resolve it pls help me on this?
